language: node_js
node_js:
- '6'
- '7'
script:
- npm run lint
- npm test
deploy:
  api_key:
    secure: KHxSUF2abDXsPWTsc8NR/W4E6Bqth6ZH64gBV4FVXFspWkPVFNfE8VJSJKlOtMvaiamBcuqdL+C30DlJnwlLsCYH/fvOq541WhZWS7ZNfBUAhuRwf2NjdH13lLcrkJbgwSiP6zGSVmRILRguyHrB9yhl8f3HQ3Xo0wUm8BDKgRWQMvE8UK/HvYr5SdmQGqMmOpUsg/8dGWxKqGpYavVo3GuR4XC6qqTLapG1A8mlbouI7267zRRUU9cg9QKbNB+zLolGtc2m6LgXCJu1JdkRrwgZ1pr6h+1ViL2m7lU4LIX3RU1xIpw/PHUQHrgG91bKBIVU2JgGpTK9GG90pC08H2MUDSi81ojQkkIJ9yd96hJOqctMRNNz8bghvkbqDssduVAp7HyAeT0KLz2LM9UTOJsamo/MpXUrCnzHDxhUBOBToWLMroxEseNDC8Lss15gioAvxcLIT1Mcq8y4Zp2HNqodhyuK7LVWRc32Sti0DaL0iOKugUoKmWbRS8vW1RmHmQvNtQdaD+Y/cFmbktk1nTEhPr7RnX8oXXcOch8hpKVAOh7nlt0I7PqYHl40ekNDVoq2ijbQg25Qm4FRBoWioLei5RX9+3Hvk76Ei0irgyiGVJ/yDZAZZ50WOSJRZITGSj0IP+JToOkDsjKtFezbTreffXVHKebZuq3uhu3PbIQ=
